### ISSUE TITLE
Set Timer w/ Microseconds?

### ISSUE THREAD

**Issue by ploderup** [duff2013/Snooze#46]
Considering the Teensy's clock has sub-microsecond length periods, it'd be nice if the timer could be set for shorter than a millisecond. Is there any simple work-around for this?

**Comment by duff2013** [comment]
It depends on what sleep mode you are using, 'DeepSleep' and 'Hibernate' would need an external pin trigger but 'Sleep' could use the Teenyduino's 'Interval Timer' which is not implemented through Snooze.

**Comment by ploderup** [comment]
Okay, I'll look into using the interval timer. Any idea how snoozing
affects writes to an SD card over SPI? I saw some comments regardings
problems with Serial.println(). Any fixes you're aware of for that (aside
from waiting)?

Best,
ploderup

**Comment by duff2013** [comment]
SD should work much quicker to work after waking from sleep mode than Serial. Nothing special should have to be done to make it work.

**Comment by ploderup** [comment]
Is there a way to sleep at full clock speed? If not, I might just see if I
can't drop power consumption by dropping the clock frequency a little.

**Comment by duff2013** [comment]
There is a function in Snooze Called 'Idle' that puts the cpu into wait mode until any interrupt happens which is usually would be systick interrupt every millisecond . You can use it for spin loops where you are waiting for something. It will lower the Teensy power usage and not side effect because the cpu and bus are not reduced.
