### ISSUE TITLE
getting time spent asleep?

### ISSUE THREAD

**Issue by ramonschepers** [duff2013/Snooze#61]
is is possible to get the time the teensy spent asleep (ms accurate) with current snooze lib or not? id like to have such a feature as it makes time critical code more reliable.

**Comment by duff2013** [comment]
Assuming your using deepSleep or hibernate then yes and no. You can use the 16 bit LPTMR timer clocked from the LPO for ~ms accuracy (that clock is not super accurate) but gives about ~65ms of total sleep time before you would have to wake the teensy and deal with the overflow. This is the Timer driver in Snooze and it adds the sleep time to the systick which mills uses. The problem is currently if you wakeup from another source then it won't add that time to the systick and mills will be off by however long you slept for. I might add in the ability to Timer driver to update the systick even if its not the wake source but then you cannot sleep for longer than ~65ms. 

Another option is the RTC but to get ms accuracy you would have to read the registers and do some fancy conversions from its crystal clock count to ms but even then won't exactly line up with ms because the clock frequency is not multiple of 1 ms.
